//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Lab3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMovies", ReplyAction="http://tempuri.org/IService1/GetAllMoviesResponse")]
        System.Xml.Linq.XElement GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMovies", ReplyAction="http://tempuri.org/IService1/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTopTenMovies", ReplyAction="http://tempuri.org/IService1/GetTopTenMoviesResponse")]
        System.Xml.Linq.XElement GetTopTenMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTopTenMovies", ReplyAction="http://tempuri.org/IService1/GetTopTenMoviesResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTopTenMoviesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC_Lab3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC_Lab3.ServiceReference1.IService1>, MVC_Lab3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public System.Xml.Linq.XElement GetTopTenMovies() {
            return base.Channel.GetTopTenMovies();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTopTenMoviesAsync() {
            return base.Channel.GetTopTenMoviesAsync();
        }
    }
}
